pipeline {
    agent  any
    stages {
        stage('Deploy') {
            steps {
                 nodejs(nodeJSInstallationName: 'nodejs') {
                    sh '''npm --version
                          sls --version
                    '''

                }
            }
        }
    }
}