pipeline {
    agent  any
    parameters{        
        choice(
            name: 'ALIAS',
            choices:"qa\nstage",
            description: "Alias of your lambda to which you wish to deploy to")        
    }
    stages {
        stage('Deploy') {
            // if (condition) {
            //     onIf
            // } else {
            //     onElse
            // }
            steps {
                 nodejs(nodeJSInstallationName: 'nodejs') {
                     script{
                        if ($ALIAS == "qa") {
                         echo "====++++ qa ++++===="
                        } else {
                         echo "====++++something else ++++===="
                        }
                     }
                     
                    sh '''npm --version
                          sls --version
                          pwd 
                          cd DMV-Messanger
                          npm install                          
                          sls deploy --masterAlias $ALIAS --retain
                    '''

                }
            }
        }
    }
}